# Generated by Django 4.1.7 on 2023-03-25 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_alter_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.account')),
                ('bitcoin', models.FloatField()),
                ('bnb', models.FloatField()),
                ('eth', models.FloatField()),
            ],
        ),
    ]
