# Generated by Django 4.1.7 on 2023-03-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_crypto_type_transaction_crypto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='bitcoin',
            new_name='BTC',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='eth',
            new_name='ETH',
        ),
    ]
